### ISSUE TITLE
ghc-8.10.3

### ISSUE THREAD

**Issue by jneira** [haskell/docker-haskell#31] opened 2020-12-25 20:54 UTC
* First of all, thanks for the great work done here
* We are using the docker image in circleci to test haskell-language-server and we are trying to add support for ghc-8.10.3 so it would be great to get that version in the docker image
* Thanks in advance!

**Comment by hvr** [comment] 2020-12-27 13:24
Javier Neira <notifications@github.com> writes:

> * First of all, thanks for the great work done here
> * We are using the docker image in circleci to test haskell-language-server and we are trying to add support for ghc-8.10.3 so it would be great to get that version in the docker image
> * Thanks in advance!

For the record, the Ubuntu packages for GHC 8.10.3 are already up in my
PPA

I'll let you know as soon as the ones for Debian (i.e.
https://downloads.haskell.org/debian/) are available as well!

**Comment by yitz-zoomin** [comment] 2021-02-01 11:57
Hi, GHC 8.10.3 has now been out for over a month. It reached Stackage LTS over a week ago. In fact, 8.10.3 is the *only* version in the the GHC 8.10.* series that is supported in Stackage LTS. Anyone relying on Stackage LTS via docker who wants to use only the official docker images cannot stay on latest LTS anymore.

(We are in that situation for our CI/CD and QA toolchains.)

So at this point it has become quite urgent to get official docker images for 8.10.3. If there is anything I can do to help, please let me know. Thanks very much!

**Comment by AlistairB** [comment] 2021-02-01 22:09
I created https://github.com/haskell-CI/haskell-ci/issues/471 for tracking this. Until Debain supports ghc 8.10.3 the issue is blocked from a docker haskell perspective.

**Comment by yitz-zoomin** [comment] 2021-02-02 15:58
Thanks @AlistairB ! Again - if there's anything we can do to help push it forward, please let me know.

**Comment by ejconlon** [comment] 2021-02-08 04:24
Hi all - I have a workaround until this issue is resolved. https://github.com/ejconlon/docker-haskell-custom uses ghcup to install recent releases. You can build your own images with the included scripts.

@hvr Would it make sense to build the official images with ghcup rather than having to build and publish apt packages? I'm loving ghcup and the quick availability of new compiler versions in it!

**Comment by AlistairB** [comment] 2021-02-15 22:36
Looks like `ghcup` may become the official default and subsume https://downloads.haskell.org/debian/ + https://launchpad.net/~hvr/+archive/ubuntu/ghc and others I guess. https://github.com/haskell-CI/haskell-ci/issues/474

In which case I guess these docker images should follow suit.

**Comment by ejconlon** [comment] 2021-02-16 20:06
If someone wants to review my changes to the base image [here](https://github.com/ejconlon/docker-haskell-custom/blob/master/images/common/Dockerfile) I would be happy to make a PR for this repo. (Also we should talk about dropping the old Debian release for new images to simplify things...)

**Comment by AlistairB** [comment] 2021-02-21 22:39
The missing ghc versions (and cabal 3.4) are now appearing https://downloads.haskell.org/debian/ :tada: I believe this is no longer blocked upstream.

**Comment by hvr** [comment] 2021-02-22 10:31
> Looks like ghcup may become the official default

For the record, even though there were some delays in packaging the new releases (GHC 9 was weakly held up because I wanted to wait for final cabal 3.4 release to batch all in one go to reduce the mental context-switch overhead), the Ubuntu PPA and Debian apt repo will continue to be supported for the foreseeable future. With future GHC versions acquiring a native codegen for aarch64 I'm strongly considering packaging up debian packages for aarch64 as well.

**Comment by psftw** [comment] 2021-04-01 01:45
8.10.3 and 8.10.4 (and 9.0.1) just merged upstream and will be available in a few hours

**Closed by psftw** 2021-04-01 01:45 UTC
